### ISSUE TITLE
Notifications only from one repo

### ISSUE THREAD

**Issue by uetam** [truveris/trac-mattermost#7]
Hi,
I have configured two repositories (1 hg and 1 git) on my trac installation however im receiving notifications only from main one which is hg. Is there a way to recieve notifications from both repositories?

**Comment by tamentis** [comment]
Frankly, we never tried to use trac-mattermost with trac repositories, I'm surprised it even works with hg, are you sure this is the plugin causing notifications? We've been using https://github.com/truveris/hg-mattermost for that. The plugin is setup as two listeners of type `ITicketChangeListener` and `IWikiChangeListener`, I really don't know how the repository changes are triggering anything.

**Comment by uetam** [comment]
Ok, thanks for your answer.
